# Generated by Django 2.2.13 on 2020-11-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201128_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagories'},
        ),
    ]
